# Generated by Django 5.2.6 on 2025-09-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='judge_file',
            field=models.FileField(blank=True, null=True, upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='ans_file',
            field=models.FileField(blank=True, null=True, upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input_file',
            field=models.FileField(blank=True, null=True, upload_to='temp/'),
        ),
    ]
