# Generated by Django 5.2.6 on 2025-09-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_testcase_score_alter_problem_judge_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='memory_limit',
            field=models.BigIntegerField(default=256000000),
        ),
        migrations.AddField(
            model_name='problem',
            name='storage_limit',
            field=models.BigIntegerField(default=1000000000),
        ),
        migrations.AddField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(default=10),
        ),
    ]
