# Generated by Django 5.1.7 on 2025-09-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_problem_memory_limit_problem_storage_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
