# Generated by Django 5.1.7 on 2025-09-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
