# Generated by Django 5.1.7 on 2025-09-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='number',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
