# Generated by Django 5.2.6 on 2025-10-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_problem_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='do_rejudge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submissiontestcase',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
