# Generated by Django 5.2.6 on 2025-10-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_submission_do_rejudge_submissiontestcase_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='temp/'),
        ),
    ]
